[package]
name = "relop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libbpf-rs = "0.20.1"
bpf-sys = "2.3.0"
libc = "0.2"
sysinfo = "0.28.4"