// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)"
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

#[path = "cpuusage.skel.rs"]
mod cpuusage_skel;

#[path = "udpflow.skel.rs"]
mod udpflow_skel;

#[path = "udpflow2.skel.rs"]
mod udpflow2_skel;

pub use cpuusage_skel::*;

pub use udpflow_skel::*;

pub use udpflow2_skel::*;
